import { useState } from 'react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { KnowledgeCrystal, Theme, THEME_CONFIGS } from '@/lib/types'
import { BookOpen, Sparkle, CheckCircle } from '@phosphor-icons/react'
import { ScrollArea } from '@/components/ui/scroll-area'

interface ArchivesViewProps {
  crystals: KnowledgeCrystal[]
  theme: Theme
  onAttune: (crystalId: string) => void
}

export function ArchivesView({ crystals, theme, onAttune }: ArchivesViewProps) {
  const [selectedCrystal, setSelectedCrystal] = useState<KnowledgeCrystal | null>(null)
  const themeConfig = THEME_CONFIGS[theme]

  const handleAttune = () => {
    if (selectedCrystal) {
      onAttune(selectedCrystal.id)
      setSelectedCrystal(null)
    }
  }

  return (
    <div className="space-y-6 p-8 max-w-6xl mx-auto">
      <div className="flex items-center gap-3">
        <BookOpen size={32} weight="fill" className="text-primary" />
        <div>
          <h1 className="text-3xl font-bold">{themeConfig.archiveLabel}</h1>
          <p className="text-muted-foreground">Knowledge crystals generated by the {themeConfig.oracleLabel}</p>
        </div>
      </div>

      {crystals.length === 0 ? (
        <Card className="glass-panel p-12 text-center">
          <Sparkle size={48} className="mx-auto mb-4 text-muted-foreground" />
          <p className="text-lg text-muted-foreground mb-2">Your {themeConfig.archiveLabel} are empty</p>
          <p className="text-sm text-muted-foreground">
            Knowledge crystals will appear here when you need help with a quest
          </p>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {crystals.map((crystal) => (
            <Card
              key={crystal.id}
              className={`glass-panel p-6 cursor-pointer transition-all hover:scale-105 border-2 ${
                crystal.isAttuned ? 'border-accent' : 'border-primary animate-pulse-glow'
              }`}
              onClick={() => setSelectedCrystal(crystal)}
            >
              <div className="flex items-start gap-4">
                <div className={`p-3 rounded-lg ${crystal.isAttuned ? 'bg-accent/20' : 'bg-primary/20'}`}>
                  {crystal.isAttuned ? (
                    <CheckCircle size={24} weight="fill" className="text-accent" />
                  ) : (
                    <Sparkle size={24} weight="fill" className="text-primary" />
                  )}
                </div>
                <div className="flex-1 space-y-2">
                  <h3 className="font-bold text-lg">{crystal.title}</h3>
                  <p className="text-sm text-muted-foreground line-clamp-2">
                    {crystal.content.substring(0, 100)}...
                  </p>
                  <div className="flex items-center gap-2">
                    {crystal.isAttuned ? (
                      <Badge variant="outline" className="text-xs">
                        Attuned
                      </Badge>
                    ) : (
                      <Badge className="bg-primary text-primary-foreground text-xs">
                        New
                      </Badge>
                    )}
                    <span className="text-xs text-muted-foreground">
                      {new Date(crystal.createdAt).toLocaleDateString()}
                    </span>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}

      <Dialog open={!!selectedCrystal} onOpenChange={() => setSelectedCrystal(null)}>
        <DialogContent className="glass-panel max-w-3xl">
          {selectedCrystal && (
            <>
              <DialogHeader>
                <div className="flex items-center gap-3">
                  <Sparkle size={32} weight="fill" className="text-primary" />
                  <DialogTitle className="text-2xl">{selectedCrystal.title}</DialogTitle>
                </div>
              </DialogHeader>
              <ScrollArea className="max-h-[60vh] mt-4">
                <div className="space-y-4 pr-4">
                  <div className="glass-panel p-6 bg-muted/20">
                    <p className="text-foreground/90 leading-relaxed whitespace-pre-wrap">
                      {selectedCrystal.content}
                    </p>
                  </div>
                  {!selectedCrystal.isAttuned && (
                    <div className="glass-panel p-4 bg-primary/10 border-2 border-primary">
                      <p className="text-sm text-muted-foreground mb-3">
                        Read this knowledge crystal to unlock your redemption quest
                      </p>
                      <Button onClick={handleAttune} className="w-full gap-2">
                        <CheckCircle size={20} weight="fill" />
                        Attune to Crystal
                      </Button>
                    </div>
                  )}
                </div>
              </ScrollArea>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
